---
- name: fecha y hora
  ansible.builtin.slurp: 
    src: "{{ sdi_commons_deploy_basedir }}deploy-xxxx.properties"
  register: passwordfile

- ansible.builtin.debug:
    msg:  "{{ passwordfile['content'] | b64decode }}"