---
- name: fecha y hora
  ansible.builtin.slurp: 
    src: "{{ sdi_commons_deploy_basedir }}deploy-xxxx.properties"
  register: passwordfile

- ansible.builtin.set_fact:
    passwordfile  "{{ passwordfile['content'] | b64decode | map('trim') | list }}"

- name: Convertir contenido a string
  set_fact:
    file_content_str: "{{ passwordfile.content | b64decode }}"

- name: Modificar texto y comentar línea anterior
  set_fact:
    modified_content: "{{ file_content_str | regex_replace('^(datasource\\..*\\.id=)(.*)$', '# \\1\n' + 'datasource.' + variable1 + '.id=' + variable2) }}"