---
- name: fecha y hora
  ansible.builtin.slurp: 
    src: "{{ sdi_commons_deploy_basedir }}deploy-xxxx.properties"
  register: passwordfile

- debug: msg="{{lookup('file', sdi_commons_deploy_basedir'deploy-xxxx.properties') }}"


- ansible.builtin.debug:
    msg:  "{{ passwordfile }}"