---
- name: fecha y hora
  ansible.builtin.shell: date "+%Y%m%d%H%M%S"
  register: fechahora

- name: concatenar nombre de atchivo de deploy con hora y fecha de sistema
  ansible.builtin.set_fact:
      nombre_ds_renombre: "{{ fechahora.stdout }}_{{ nombre_archivo_deploy }}_{{ fechahora.stdout }}"

- name: Respaldo de archivo de deploy de JBOSS
  ansible.builtin.shell: "mv {{ sdi_commons_deploy_basedir }}{{ nombre_archivo_deploy }} {{ sdi_commons_deploy_basedir }}{{ nombre_ds_renombre }}"

- name: crear archivo de deploy
  ansible.builtin.template:
    src: templates/deploy-xxxx.properties.j2
    dest: "{{ sdi_commons_deploy_basedir }}{{ nombre_archivo_deploy }}"

- name: creacion de Shell Script para despliegue de modificacion
  ansible.builtin.template:
    src: templates/jboss.j2
    dest: "{{ SdiCommonsDeploy }}deploy.sh"