---
- name: Lectura de archivo de deploy
  ansible.builtin.slurp: 
    src: "{{ sdi_commons_deploy_basedir }}deploy-xxxx.properties"
  register: passwordfile

- name: Convertir contenido a string
  set_fact:
    file_content_str: "{{ passwordfile.content | b64decode }}"

- name: Concatenate a list to string
  set_fact:
    file_split_n: "{{ file_content_str.split('\n') }}"

- name: Modificar texto y comentar línea anterior
  set_fact:
    modified_content: "{{ file_split_n | regex_replace('^(datasource\\..*\\.id=)(.*)$', '# \\1\n' + 'datasource.' + variable1 + '.id=' + variable2) }}"

- name: listado de modificacion
  debug: 
    msg: "{{ modified_content }}"

# - name: Modificar texto y comentar línea anterior
#   set_fact:
#     modified_content: "{{ item | regex_replace('^(datasource\\..*\\.id=)(.*)$', '# \\1\n' + 'datasource.' + variable1 + '.id=' + variable2) }}"
#   with_items: "{{ file_split_n }}"
#   register: contenido

# - name: listado de modificacion
#   debug: 
#     msg: "{{ item }}"
#   with_items:  "{{ contenido.results }}"
  